name: ChatTranslator
version: 1.1
author: Samuel98 (SamzRulez)
website: http://www.samuelzcloud.co.uk/
description: Chat Translation which is done by the free Yandex Translate API.

softdepend: [Herochat, Vault]

main: uk.co.samuelzcloud.dev.plugins.ChatTranslator.ChatTranslator

commands:
  ChatTranslator:
    description: View and maintain the plugin information.
    usage: /<command> <Info | Save | Load>
    aliases: []
  Language:
    description: Choose your preffered language.
    usage: /<command>
    aliases: [Lang, Chat]

permissions:
  ChatTranslator.Admin:
    description: Permission to all features and commands.
    default: op
    children:
    - ChatTranslator.Language: true
    - ChatTranslator.Info: true
    - ChatTranslator.Load: true
    - ChatTranslator.Save: true
  ChatTranslator.Language:
    description: Permission to change your preffered language.
    default: true
  ChatTranslator.Info:
    description: Permission to view the plugin information.
    default: true
  ChatTranslator.Load:
    description: Permission to force a load of configs.
    default: op
  ChatTranslator.Save:
    description: Permission to force a save of configs.
    default: op
